webtalk_init -webtalk_dir /tmp/v/parviv/parallella_7020_headless_gpiose_elink2.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jun 22 20:07:55 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "2030437_206273328_210558805_645" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "h50cct38d3gu9el3biejghcq2j" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Gentoo" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Gentoo Base System release 2.2" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1434995745000" -context "sdk\\\\hardware/1434995745000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1434995745000"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1434995745000"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1434995745000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1434995745000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1434995745000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1434995745000"
webtalk_add_data -client sdk -key uid -value "1434995774000" -context "sdk\\\\bsp/1434995774000"
webtalk_add_data -client sdk -key hwid -value "1434995745000" -context "sdk\\\\bsp/1434995774000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1434995774000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1434995774000"
webtalk_add_data -client sdk -key uid -value "1434995778000" -context "sdk\\\\application/1434995778000"
webtalk_add_data -client sdk -key hwid -value "1434995745000" -context "sdk\\\\application/1434995778000"
webtalk_add_data -client sdk -key bspid -value "1434995774000" -context "sdk\\\\application/1434995778000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1434995778000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1434995778000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1434995778000"
webtalk_transmit -clientid 3998508226 -regid "2030437_206273328_210558805_645" -xml /tmp/v/parviv/parallella_7020_headless_gpiose_elink2.sdk/webtalk/usage_statistics_ext_sdk.xml -html /tmp/v/parviv/parallella_7020_headless_gpiose_elink2.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /tmp/v/parviv/parallella_7020_headless_gpiose_elink2.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
